- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Adjust path if necessary

  tasks:
    - name: Pull Docker image
      docker_image:
        name: kavyasulakhe/addressbook:1.3
        source: pull

    - name: Run Docker container
      docker_container:
        name: addressbook
        image: kavyasulakhe/addressbook:1.3
        ports:
          - "8093:8080"
